export const ROUND_FINISHED     = 'roundFinished'
export const PREPARE_SHUFFLING  = 'prepareShuffling'
export const SHUFFLING          = 'shuffling'
export const DEALING            = 'dealing'
export const HAND_DEALT         = 'handDealt'
export const CHOICE_MADE        = 'choiceMade'